"""normalize legacy nullability

Revision ID: 0a413d5bc35d
Revises: 4b8ca3208330
Create Date: 2026-10-01 15:13:00.357687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0a413d5bc35d"
down_revision: Union[str, None] = "4b8ca3208330"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.alter_column(
            "factor",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("1"),
        )

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column(
            "ideal_stock",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("productsupplier", schema=None) as batch_op:
        batch_op.alter_column(
            "frequency",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("'semanal'"),
        )
        batch_op.alter_column(
            "week_parity",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("productsupplier", schema=None) as batch_op:
        batch_op.alter_column(
            "week_parity",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "frequency",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("'semanal'"),
        )

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column(
            "ideal_stock",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.alter_column(
            "factor",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("1"),
        )

    # ### end Alembic commands ###
