"""baseline

Revision ID: 4b8ca3208330
Revises:
Create Date: 2026-10-01 15:10:15.611051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4b8ca3208330"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cashregister",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opened_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("opened_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("opening_amount", sa.Float(), nullable=False),
        sa.Column("closed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("closed_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("closing_amount", sa.Float(), nullable=True),
        sa.Column("expected_amount", sa.Float(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("opening_details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("system_totals", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("closing_details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cpf_cnpj", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("neighborhood", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("complement", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customer_cpf_cnpj"), ["cpf_cnpj"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_customer_name"), ["name"], unique=False)

    op.create_table(
        "paymentmethod",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sale",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "setting",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "supplier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cnpj", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("neighborhood", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplier_cnpj"), ["cnpj"], unique=False)
        batch_op.create_index(batch_op.f("ix_supplier_name"), ["name"], unique=False)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "bill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("suplyer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("bill_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("days", sa.Integer(), nullable=True),
        sa.Column("payday", sa.DateTime(), nullable=True),
        sa.Column(
            "value_from_payment", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("bar_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pix_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pix_payload", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pix_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("date_from_add", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cash_movement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cash_register_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cash_register_id"],
            ["cashregister.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=False),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("discount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["paymentmethod.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("barcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secondary_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("suppliers", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.Column("ideal_stock", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("barcode"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("factor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["paymentmethod.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column(
            "barcode", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True
        ),
        sa.Column("factor", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("barcode"),
    )
    with op.batch_alter_table("product_unit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_unit_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "productmovement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "productsupplier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("delivery_day", sa.Integer(), nullable=False),
        sa.Column("lead_time", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("week_parity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("productsupplier", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_productsupplier_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_productsupplier_supplier_id"), ["supplier_id"], unique=False
        )

    op.create_table(
        "purchase_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nf_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nf_serie", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nf_chave", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nf_modelo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("freight", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("net_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "receivable",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("paid_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("obs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tab",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("identification", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("print_count", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("canceled_at", sa.DateTime(), nullable=True),
        sa.Column("opened_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("closed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("canceled_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number", name="uq_tab_number"),
    )
    op.create_table(
        "purchase_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("barcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("product_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("unit_com", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchase_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "receivable_payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receivable_id", sa.Integer(), nullable=False),
        sa.Column("method_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cash_movement_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cash_movement_id"],
            ["cash_movement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["method_id"],
            ["paymentmethod.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receivable_id"],
            ["receivable.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tab_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tab_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("factor", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tab_id"],
            ["tab.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tab_item")
    op.drop_table("receivable_payment")
    op.drop_table("purchase_item")
    op.drop_table("tab")
    op.drop_table("receivable")
    op.drop_table("purchase_order")
    with op.batch_alter_table("productsupplier", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_productsupplier_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_productsupplier_product_id"))

    op.drop_table("productsupplier")
    op.drop_table("productmovement")
    with op.batch_alter_table("product_unit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_unit_product_id"))

    op.drop_table("product_unit")
    op.drop_table("order_payments")
    op.drop_table("order_items")
    op.drop_table("product")
    op.drop_table("orders")
    op.drop_table("cash_movement")
    op.drop_table("bill")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_name"))
        batch_op.drop_index(batch_op.f("ix_supplier_cnpj"))

    op.drop_table("supplier")
    op.drop_table("setting")
    op.drop_table("sale")
    op.drop_table("paymentmethod")
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_name"))
        batch_op.drop_index(batch_op.f("ix_customer_cpf_cnpj"))

    op.drop_table("customer")
    op.drop_table("category")
    op.drop_table("cashregister")
    op.drop_table("audit_event")
    op.drop_table("account")
    # ### end Alembic commands ###
