"""add purchase_item.factor

Revision ID: bbb85e66961d
Revises: 0a413d5bc35d
Create Date: 2026-10-01 15:43:43.475356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "bbb85e66961d"
down_revision: Union[str, None] = "0a413d5bc35d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purchase_item", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "factor",
                sa.Integer(),
                nullable=False,
                server_default="1",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purchase_item", schema=None) as batch_op:
        batch_op.drop_column("factor")

    # ### end Alembic commands ###
